# Generated by Django 3.0.8 on 2020-07-15 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
        ('purchase', '0001_initial'),
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否有效')),
                ('status', models.CharField(choices=[('N', '尚未付款'), ('A', '全部付款'), ('P', '部分付款'), ('O', '超额付款')], default='N', max_length=1, verbose_name='状态')),
                ('dued', models.DateField(verbose_name='应付日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('arrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Arrive', verbose_name='对应到货单')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='建立人员')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Supplier', verbose_name='供货商')),
            ],
            options={
                'verbose_name': '应付帐款',
                'verbose_name_plural': '应付帐款',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(help_text='付款时必须输入供货商提供的发票号码', max_length=12, verbose_name='发票号码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_delay', models.BooleanField(default=False, verbose_name='是否延迟')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='付款时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='建立人员')),
                ('due', models.ForeignKey(help_text='仅显示"有效"且非"全部付款"的应付帐款', on_delete=django.db.models.deletion.CASCADE, to='finance.Due', verbose_name='对应应付帐款')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Supplier', verbose_name='供货商')),
            ],
            options={
                'verbose_name': '付款单',
                'verbose_name_plural': '付款单',
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否有效')),
                ('status', models.CharField(choices=[('N', '尚未收款'), ('A', '全部收款'), ('P', '部分收款'), ('O', '超额收款')], default='N', max_length=1, verbose_name='状态')),
                ('receivabled', models.DateField(verbose_name='应收日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='建立人员')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Customer', verbose_name='客户')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Ship', verbose_name='对应出货单')),
            ],
            options={
                'verbose_name': '应收帐款',
                'verbose_name_plural': '应收帐款',
            },
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(help_text='收款时必须登打发票号码', max_length=12, verbose_name='发票号码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_delay', models.BooleanField(default=False, verbose_name='是否延迟')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='收款时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='建立人员')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Customer', verbose_name='客户')),
                ('receivable', models.ForeignKey(help_text='仅显示"有效"且非"全部收款"的应收帐款', on_delete=django.db.models.deletion.CASCADE, to='finance.Receivable', verbose_name='对应应收帐款')),
            ],
            options={
                'verbose_name': '收款单',
                'verbose_name_plural': '收款单',
            },
        ),
        migrations.CreateModel(
            name='ReceiveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='金额')),
                ('discount', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='折扣')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='汇率')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Currency', verbose_name='币别')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Product', verbose_name='商品')),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Receive', verbose_name='收款单单头')),
            ],
            options={
                'verbose_name': '收款单单身',
                'verbose_name_plural': '收款单单身',
            },
        ),
        migrations.CreateModel(
            name='ReceivableDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='金额')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Currency', verbose_name='币别')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Product', verbose_name='商品')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Receivable', verbose_name='应收帐款单头')),
            ],
            options={
                'verbose_name': '应收帐款单身',
                'verbose_name_plural': '应收帐款单身',
            },
        ),
        migrations.CreateModel(
            name='PayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='金额')),
                ('discount', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='折扣')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='汇率')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Currency', verbose_name='币别')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Material', verbose_name='原料')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Pay', verbose_name='付款单单头')),
            ],
            options={
                'verbose_name': '付款单单身',
                'verbose_name_plural': '付款单单身',
            },
        ),
        migrations.CreateModel(
            name='DueDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='金额')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Currency', verbose_name='币别')),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Due', verbose_name='应付帐款单头')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Material', verbose_name='原料')),
            ],
            options={
                'verbose_name': '应付帐款单身',
                'verbose_name_plural': '应付帐款单身',
            },
        ),
    ]
