# Generated by Django 3.0.8 on 2020-07-15 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否有效')),
                ('description', models.CharField(max_length=256, verbose_name='申请原因')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='异动日期')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='异动人员')),
            ],
            options={
                'verbose_name': '原料库存异动申请单',
                'verbose_name_plural': '原料库存异动申请单',
            },
        ),
        migrations.CreateModel(
            name='Pcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否有效')),
                ('description', models.CharField(max_length=256, verbose_name='申请原因')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='异动日期')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='异动人员')),
            ],
            options={
                'verbose_name': '商品库存异动申请单',
                'verbose_name_plural': '商品库存异动申请单',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='请注意，存盘后，下方制程单单身的"原料数量"将会自动乘上此"商品制程数量"', verbose_name='商品制程数量')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('status', models.CharField(choices=[('A', '立单申请'), ('C', '原料已出库'), ('R', '商品已入库')], default='A', max_length=1, verbose_name='制程状况')),
                ('claimed', models.DateTimeField(null=True, verbose_name='原料出库日期')),
                ('receipted', models.DateTimeField(null=True, verbose_name='商品入库时间')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='申请日期')),
                ('claim_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_process', to=settings.AUTH_USER_MODEL, verbose_name='原料出库确认人员')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='申请人员')),
                ('order', models.ForeignKey(help_text='仅显示"尚未出货"的订单', limit_choices_to={'status': 'N'}, on_delete=django.db.models.deletion.CASCADE, to='sale.Order', verbose_name='对应订单')),
                ('product', models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.CASCADE, to='basic.Product', verbose_name='对应商品')),
                ('receipt_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_process', to=settings.AUTH_USER_MODEL, verbose_name='商品入库确认人员')),
            ],
            options={
                'verbose_name': '制程单',
                'verbose_name_plural': '制程单',
                'permissions': (('check_process', '可确认制程单内商品与原料的出入库'),),
            },
        ),
        migrations.CreateModel(
            name='Ptran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_form', models.CharField(choices=[('SHIP', '出货单'), ('PCHECK', '商品库存异动申请单'), ('PROCESS', '制程单')], default='', max_length=12, verbose_name='来源单类别')),
                ('source_id', models.PositiveIntegerField(default=0, verbose_name='来源单号')),
                ('from_quantity', models.PositiveIntegerField(default=0, verbose_name='异动前数量')),
                ('tran_quantity', models.IntegerField(default=0, verbose_name='异动数量')),
                ('to_quantity', models.PositiveIntegerField(default=0, verbose_name='异动后数量')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='异动日期')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='异动人员')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品库存异动',
                'verbose_name_plural': '商品库存异动',
            },
        ),
        migrations.CreateModel(
            name='ProcessDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Material', verbose_name='原料')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Process', verbose_name='制程单')),
            ],
            options={
                'verbose_name': '制程单单身',
                'verbose_name_plural': '制程单单身',
            },
        ),
        migrations.CreateModel(
            name='PcheckDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('quantity', models.IntegerField(help_text='数量为正表示新增一个库存，数量为负表示减少一个库存', verbose_name='异动数量')),
                ('pcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Pcheck', verbose_name='商品库存异动申请单')),
                ('product', models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='basic.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品库存异动申请单单身',
                'verbose_name_plural': '商品库存异动申请单单身',
            },
        ),
        migrations.CreateModel(
            name='Mtran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_form', models.CharField(choices=[('ARRIVE', '到货单'), ('MCHECK', '原料库存异动申请单'), ('PROCESS', '制程单')], default='', max_length=12, verbose_name='来源单类别')),
                ('source_id', models.PositiveIntegerField(default=0, verbose_name='来源单号')),
                ('from_quantity', models.PositiveIntegerField(default=0, verbose_name='异动前数量')),
                ('tran_quantity', models.IntegerField(default=0, verbose_name='异动数量')),
                ('to_quantity', models.PositiveIntegerField(default=0, verbose_name='异动后数量')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='异动日期')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='异动人员')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Material', verbose_name='原料')),
            ],
            options={
                'verbose_name': '原料库存异动',
                'verbose_name_plural': '原料库存异动',
            },
        ),
        migrations.CreateModel(
            name='McheckDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('quantity', models.IntegerField(help_text='数量为正表示新增一个库存，数量为负表示减少一个库存', verbose_name='异动数量')),
                ('material', models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='basic.Material', verbose_name='原料')),
                ('mcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Mcheck', verbose_name='原料库存异动申请单')),
            ],
            options={
                'verbose_name': '原料库存异动申请单单身',
                'verbose_name_plural': '原料库存异动申请单单身',
            },
        ),
    ]
