# Generated by Django 3.0.8 on 2020-07-15 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='组成数量')),
            ],
            options={
                'verbose_name': 'BOM表',
                'verbose_name_plural': 'BOM表',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Part Number')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('status', models.CharField(choices=[('W', '等待审核'), ('A', '已审核'), ('S', '停止使用')], default='W', max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '原料种类',
                'verbose_name_plural': '原料种类',
                'permissions': (('audit_category', '可审核原料种类'), ('stop_category', '可终止原料种类')),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='币别代号')),
                ('title', models.CharField(max_length=8, verbose_name='币别')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='汇率')),
            ],
            options={
                'verbose_name': '币别',
                'verbose_name_plural': '币别',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='料号')),
                ('image_sub', models.CharField(max_length=64, verbose_name='图文件在google共享文件夹的位置')),
                ('price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='未税价')),
                ('tax', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='税金')),
                ('tax_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='含税价')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('status', models.CharField(choices=[('W', '等待审核'), ('A', '已审核'), ('S', '停止使用')], default='W', max_length=1, verbose_name='状态')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('category', models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='basic.Category', verbose_name='种类')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Currency', verbose_name='报价币别')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
                'permissions': (('audit_material', '可审核原料'), ('stop_material', '可终止原料')),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Part Number')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('status', models.CharField(choices=[('W', '等待审核'), ('A', '已审核'), ('S', '停止使用')], default='W', max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '商品Part',
                'verbose_name_plural': '商品Part',
                'permissions': (('audit_part', '可审核商品Part'), ('stop_part', '可终止商品Part')),
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='帐期名称')),
                ('period', models.PositiveIntegerField(help_text='天数为整数', verbose_name='天数')),
            ],
            options={
                'verbose_name': '帐期',
                'verbose_name_plural': '帐期',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='size')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('status', models.CharField(choices=[('W', '等待审核'), ('A', '已审核'), ('S', '停止使用')], default='W', max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '商品Size',
                'verbose_name_plural': '商品Size',
                'permissions': (('audit_size', '可审核商品Size'), ('stop_size', '可终止商品Size')),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('contacter', models.CharField(blank=True, max_length=32, verbose_name='联络人')),
                ('landline', models.CharField(blank=True, max_length=16, verbose_name='联络市话')),
                ('mobile', models.CharField(blank=True, help_text='ex:12345678901', max_length=16, verbose_name='联络手机号')),
                ('wechat_account', models.CharField(blank=True, max_length=16, verbose_name='联络微信账号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='联络email')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='联络地址')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('status', models.CharField(choices=[('W', '等待审核'), ('A', '已审核'), ('S', '停止使用')], default='W', max_length=1, verbose_name='状态')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Period', verbose_name='帐期')),
            ],
            options={
                'verbose_name': '供货商',
                'verbose_name_plural': '供货商',
                'permissions': (('audit_supplier', '可审核供货商'), ('stop_supplier', '可终止供货商')),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Model Name')),
                ('image_sub', models.CharField(max_length=64, verbose_name='图文件在google共享文件夹的位置')),
                ('price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='未税价')),
                ('tax', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='税金')),
                ('tax_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='含税价')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('status', models.CharField(choices=[('W', '等待审核'), ('A', '已审核'), ('S', '停止使用')], default='W', max_length=1, verbose_name='状态')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('combines', models.ManyToManyField(through='basic.Bom', to='basic.Material')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Currency', verbose_name='报价币别')),
                ('part', models.ForeignKey(blank=True, limit_choices_to={'status': 'A'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.Part', verbose_name='Part Number')),
                ('size', models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='basic.Size', verbose_name='size')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'permissions': (('audit_product', '可审核商品'), ('stop_product', '可终止商品')),
            },
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Supplier', verbose_name='供货商'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('contacter', models.CharField(blank=True, max_length=32, verbose_name='联络人')),
                ('landline', models.CharField(blank=True, max_length=16, verbose_name='联络市话')),
                ('mobile', models.CharField(blank=True, help_text='ex:12345678901', max_length=16, verbose_name='联络手机号')),
                ('wechat_account', models.CharField(blank=True, max_length=16, verbose_name='联络微信账号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='联络email')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='联络地址')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('status', models.CharField(choices=[('W', '等待审核'), ('A', '已审核'), ('S', '停止使用')], default='W', max_length=1, verbose_name='状态')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic.Period', verbose_name='帐期')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'permissions': (('audit_customer', '可审核客户'), ('stop_customer', '可终止客户')),
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='material',
            field=models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='basic.Material', verbose_name='原料'),
        ),
        migrations.AddField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Product', verbose_name='商品'),
        ),
    ]
