# Generated by Django 3.0.8 on 2020-07-15 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(choices=[('1', 'CAT1'), ('2', 'CAT2'), ('3', 'CAT3')], max_length=2, verbose_name='Cat.')),
                ('pi_no', models.CharField(max_length=16, unique=True, verbose_name='PI #')),
                ('po_no', models.CharField(blank=True, max_length=16, verbose_name='PO #')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_urgency', models.BooleanField(default=False, verbose_name='是否为急单')),
                ('status', models.CharField(choices=[('N', '尚未出货'), ('A', '全部出货'), ('P', '部分出货'), ('O', '超额出货')], default='N', max_length=1, verbose_name='状态')),
                ('etd', models.DateField(verbose_name='预定出货日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='订购时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='建立人员')),
                ('customer', models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='basic.Customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'permissions': (('active_order', '可中止订单'),),
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否有效')),
                ('is_delay', models.BooleanField(default=False, verbose_name='是否延迟')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='出货时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='建立人员')),
                ('customer', models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.PROTECT, to='basic.Customer', verbose_name='客户')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.Order', verbose_name='对应订单')),
            ],
            options={
                'verbose_name': '出货单',
                'verbose_name_plural': '出货单',
                'permissions': (('active_ship', '可中止出货单'),),
            },
        ),
        migrations.CreateModel(
            name='ShipDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('quantity', models.PositiveIntegerField(verbose_name='出货数量')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Product', verbose_name='出货商品')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Ship', verbose_name='出货单单头')),
            ],
            options={
                'verbose_name': '出货单单身',
                'verbose_name_plural': '出货单单身',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=2, verbose_name='单身项次')),
                ('quantity', models.PositiveIntegerField(verbose_name='订购数量')),
                ('price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='未税金额')),
                ('tax', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='税金')),
                ('tax_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='含税金额')),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='小计未税金额')),
                ('tax_subtotal', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='小计含税金额')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='描述')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic.Currency', verbose_name='币别')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Order', verbose_name='订单单头')),
                ('product', models.ForeignKey(limit_choices_to={'status': 'A'}, on_delete=django.db.models.deletion.DO_NOTHING, to='basic.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单单身',
                'verbose_name_plural': '订单单身',
            },
        ),
    ]
